<?php

$this->layout()->searchbox = false;

$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

$errorsHelper  = $this->plugin('formelementerrors');
$errorsHelper->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>');

if (empty($form->admin)) {
    $form->setAttribute('action', $this->url('dpub-upload'));
} else { 
    $form->setAttribute('action', $this->url('dpub-edit'));
}

// Admin should be able to do temp file manipulations
$fileadmin = $form->get('opus:status')->getValue()=='neu' ? true : false;
// error_log('metadata status ' . $form->get('opus:status')->getValue());

// Count page form elements
$count = 0;
echo $this->form()->openTag($form);
?>

<?/* Helper to rename files */?>
<script type="text/javascript">
    function replace(number) {
        var node = document.getElementById('opus:fileadmin'+number);
        var old = document.getElementById('opus:filename'+number).textContent;
        node.setAttribute('onclick','');
        node.innerHTML = '<input name="opus:fileadmin" placeholder="'
            +   old + '" title="New Name" size="34" value=""/>'
            + '<input name="opus:filename" type="hidden" value="'+old+'"/>';
    }
</script>

<?/* Metadata head line */?>
<p>
<div class="dpub">
  <legend><div class="row">
    <div class="col-sm-8">
    <?php 
      if ($form->admin) {
          $page = $form->page->getValue();
          $content = $this->url('content-page', ['page' => 'dpub-'.$page]);
          // if ($form->page->getValue()==3) {
          //     $content = $this->url('content-page', ['page' => 'options']);
          // }
	      echo '<a href="'.$content.'" rel="nofollow"';
          echo ' title="'.$this->translate('Help').'" data-lightbox>';
          echo '<small><i class="fa fa-fw fa-empire" aria-hidden="true"></i>';
          echo '</small></a> ';
      }
      echo ($this->legend) ?: $this->translate($form->title); 
      echo ' # '. $form->page->getValue() . ' / ' . $form->end;
    ?>
    </div>
    <div class="col-sm-4">
    <button class="btn btn-primary" type="submit" name="submit" title="<?=$this->transEsc('Get more information')?>" style="border:0px solid transparent"><?=$this->transEsc('Submit')?></button>
    <button class="btn btn-secondary" type="submit" name="back" value="back" style="border:0px solid transparent"><?=$this->transEsc('navigate_back')?></button>
    </div>
  </div>
  </legend>

<?php echo $this->formHidden($form->page);

foreach($form->terms as $term) {

	if ($term[2]=='separator' && $form->page->getValue()==$term[3] ) {
		echo $this->translate($term[1]);
		continue;
	} else if ($term[2]=='separator') {
		continue;
	} else if ($term[2]=='message' && $form->page->getValue()==$term[3]) {
        $count++;
		echo '<small><pre>'.$this->translate($term[1]);
        echo '</pre></small>';
		continue;
    } else if ($term[2]=='message') {
		continue;
	} else if ($form->page->getValue() != $term[3] && $term[0]=='opus:file') {
		continue;
	} else if ($form->page->getValue() != $term[3]) {
		echo $this->formHidden($form->get($term[0]));
		continue;
	} else if ($form->page->getValue() == $term[3]) {
        $count++; // count all elements to display
	}

	$elem = $form->get($term[0]);
	$errors = $elem->getMessages();
	$errorClass = (!empty($errors)) ? ' error' : '';

    // Metadata page elements
    // error_log('GH201911 ' . $form->page->getValue() .' '. $term[3]);
    // render first row : form label
	echo '<div class="row">';
    if (substr($term[0],0,15)=='dcterms:creator') {
        // GH2020-11 authorid ORCID or GND
	    echo '<div class="control-group '.$errorClass.' col-sm-9">';
        echo $this->translate($elem->getLabel());
        echo '</div>'."\n";
	    echo '<div class="control-group '.$errorClass.' col-sm-3">';
        $sub = $form->get('opus:authorid'.substr($term[0],15));
		echo '<a href="'.$this->url('content-page', ['page' => 'authorid']).'"';
		echo ' rel="nofollow" data-lightbox>';
        echo $this->translate($sub->getLabel());
        echo '</a></div>'."\n";
    } else if (substr($term[0],0,13)=='opus:authorid') {
        // 
    } else if (!empty($term[5]) && is_array($term[5]) && $term[5][2]=='ref2') {
        $sub = $form->get($term[5][1]);
	    echo '<div class="control-group '.$errorClass.' col-sm-8">';
        echo $this->translate($elem->getLabel()) . '</div>'."\n";;
	    echo '<div class="control-group '.$errorClass.' col-sm-4">';
        echo $this->translate($sub->getLabel()) . '</div>'."\n";
    } else if ($term[2]=='collection') {
        // 
    } else {
        // render form label
	    echo '<div class="help-group col-sm-6">';
	    if ($term[2] == 'file') {
	        if ($form->admin && count($form->files)==0 && !$fileadmin) {
                // zero files, metadata only request
            } else {
                echo '<hr><strong>';
                echo $this->translate('Dpub::'.$elem->getLabel());
                echo '</strong>';
                if (empty($form->admin)) {
                    echo '</div><div><hr><a href="';
                    echo $this->url('content-page', ['page' =>'files']);
	                echo '" rel="nofollow" data-lightbox>';
                    echo $this->translate('Dpub::filesubmit');
                    echo '</a>'."\n";
                }
		    }
	    } else if ($term[0] == 'opus:filecount') {
            // Nothing
	    } else if ($term[0] == 'opus:volume') {
            // Nothing
	    } else if ($term[0] == 'opus:status') {
            // Nothing
	    } else if ($term[0] == 'opus:options') {
            $elem->setAttribute("onchange", "this.form.submit()");
            if (!empty($elem->getValue())) {
                error_log('*** ' . $term[0] . ' ' . $elem->getValue());
            }
	    //} else if ($term[0] == 'opus:details') {
        //    if (!empty($elem->getValue())) {
        //        error_log('*** ' . $term[0] . ' ' . $elem->getValue());
        //    }
	    } else if (empty($elem->getLabel())) {
            // error_log("empty label " . $term[0]);
	    } else if (empty($term[4])) {
            echo $this->translate($elem->getLabel());
        } else { 
            // required
            echo '<strong>'.$this->translate($elem->getLabel()).'</strong>';
        }
        if ($elem->hasAttribute('lang') && strpos($term[0], 'abstract')) {
            echo ' ' . $this->translate($elem->getAttribute('lang'));
        }
        echo '</div>'."\n";
    }
    echo '</div>'.PHP_EOL;

    // render second row : first column : main form
	echo '<div class="row">';
	if (is_array($term[2])) {
        if (!empty($elem->getEmptyOption())) {
            $elem->setEmptyOption($this->translate($elem->getEmptyOption()));
        }
        if ($term[0]=='opus:domain') {
            $elem->setAttribute('class', 'form-element col-sm-3');
		    echo $this->formSelect($elem);
		    echo $errorsHelper($elem);
            echo '<span class="col-sm-5">oid: ';
            echo $form->get('opus:source_opus')->getValue().'</span>';
	    } else if ($term[0]=='opus:serial') {
            $elem->setAttribute('class', 'form-element col-sm-7');
		    echo $this->formSelect($elem);
		    echo $errorsHelper($elem);
            echo '<span class="col-sm-1"></span>';
	    } else if ($term[0]==='dcterms:language' || $term[0]==='dcterms:type') {
            $options = [];
            foreach($elem->getValueOptions() as $val=>$item) {
                $options += [ $val => $this->translate($item) ];
            }
            $elem->setValueOptions($options);
            $elem->setAttribute('class', 'form-element col-sm-4');
		    echo $this->formSelect($elem);
		    echo $errorsHelper($elem);
	    } else if ($term[0]=='opus:collection') {
             $elem->setAttribute('class', 'form-element col-sm-6');
		     echo $this->formSelect($elem);
		     echo $errorsHelper($elem);
	    } else {
            $elem->setAttribute('class', 'form-element col-sm-6');
		    echo $this->formSelect($elem);
		    echo $errorsHelper($elem);
        }
	} else if ($term[2] == 'text' && strpos($term[0], 'creator')) {
        $elem->setAttribute('class', 'form-element col-sm-5');
		echo $this->formText($elem);
		echo $errorsHelper($elem);
	} else if ($term[2] == 'text') {
        $elem->setAttribute('class', 'form-element col-sm-6');
		echo $this->formText($elem);
		echo $errorsHelper($elem);
	} else if ($term[2] == 'area' && strpos($term[0], 'abstract')) {
        $elem->setAttribute('class', 'form-element col-sm-12');
		echo $this->formTextarea($elem);
		echo $errorsHelper($elem);
	} else if ($term[2] == 'area') {
        $elem->setAttribute('class', 'form-element col-sm-8');
		echo $this->formTextarea($elem);
		echo $errorsHelper($elem);
	} else if ($term[2] == 'date') {
        $elem->setAttribute('class', 'form-element col-sm-3');
		echo $this->formDate($elem);
		echo $errorsHelper($elem);
	} else if ($term[2] == 'year') {
        $elem->setAttribute('class', 'col-sm-2');
		echo $this->formNumber($elem);
		echo $errorsHelper($elem);
	} else if ($term[2] == 'number' && $term[0]!='opus:filecount') {
        $elem->setAttribute('class', 'form-element col-sm-2');
		echo $this->formNumber($elem);
		echo $errorsHelper($elem);
	} else if ($term[2] == 'email') {
        $elem->setAttribute('class', 'form-element col-sm-4');
		echo $this->formEmail($elem);
		echo $errorsHelper($elem);
	} else if ($term[2] == 'subject') {
        $elem->setAttribute('class', 'form-element col-sm-8');
		echo $this->formTextarea($elem);
		echo $errorsHelper($elem);
        if (!$form->admin) {
		    echo '&nbsp;<i class="fa fa-genderless"></i>';
		    echo ' <a href="'.$this->url('dpub-subject').'" rel="nofollow"';
		    echo ' data-lightbox><button class="btn btn-secondary"';
		    echo ' <button class="btn btn-secondary">GND</button></a>';
        }
	} else if ($term[2] == 'file') {
	    if ($form->admin && !$fileadmin) {
            // use status info from temp table to supress file upload
        } else {
		    echo '<div class="form-element col-sm-7">';
            echo $this->formFile($elem);
            echo $this->formElementErrors($elem);
		    echo '</div>';
		    echo '<div class="form-element"><small>';
            $check = $form->get('opus:filecount');
            echo $this->translate($check->getLabel()) . ': ';
            echo $this->formNumber($check);
		    echo '</small></div>';
        }
	} else if ($term[2] == 'checkbox') {
        $elem->setAttribute('class', 'form-check-input col-sm-1');
        echo $this->formCheckbox($elem); // .' '.$this->translate($term[1]);
        echo $this->formElementErrors($elem);
	} else if ($term[2] == 'collection') {
        $elem->setAttribute('class', 'form-element col-sm-1');
		echo '<div class="form-element col-sm-9"><small>';
		echo $elem->getLabel();
		echo $this->formCheckbox($elem);
		echo '</small></div>';
    } else if ($term[2] == 'text2') {
        // rendered elsewhere
    } else if ($term[2] == 'number') {
        // rendered elsewhere
    } else {
        error_log('GH2021-04-23 metadata zero '.$term[2].' '.$form->page->getValue());
    }

    // render second column : text or secondary element
	if (empty($term[5])) {
		// zero text
    } else if (substr($term[0],0,13)=='opus:authorid') {
        //
	} else if (is_array($term[5]) && $term[5][2]==='ref2') {
        $sub = $form->get($term[5][1]); 
        $sub->setAttribute('class', 'col-sm-3');
        // error_log('sub ' . $sub->getName());
        // echo '<div class="form-element col-sm-3">';
        // echo $this->formText($sub).'</div>';
        echo $this->formText($sub);
	} else if (is_array($term[5]) && $term[5][2]==='ref') {
        if (isset($term[5][3])) {
            echo '<div class="form-element col-sm-8" id="'.$term[5][3].'">';
        } else {
            echo '<div class="form-element col-sm-8">';
        }
        if ($term[5][1]==='login') {
            echo ' <a href="' . $this->url('myresearch-userlogin') 
                . '" rel="nofollow" data-lightbox>';
        } else {
            echo ' <a href="'
                . $this->url('content-page', ['page'=>$term[5][1]])
                . '" rel="nofollow" data-lightbox>';
        }
		echo $this->translate($term[5][0]).'</a>';
        echo '</div><div><br/><br/></div>';
	} else if ($term[0]=='opus:uid') {
        echo '<div>';
        // echo $this->formHidden($form->get($term[0]));
        echo '<button class="btn btn-secondary" type="submit" name="callnum">';
        echo $this->transEsc($term[5]).'</button></div>';
        echo '<div><br/></div>';
    } else if (substr($term[0],0,15)=='dcterms:creator') {
        // GH202011 authorid ORCID or GND
        $sub = $form->get('opus:authorid'.substr($term[0],15));
        echo '<div class="form-element col-sm-3">';
        echo $this->translate($term[5][0]).'</div>';
		echo '<div class="form-element col-sm-3">';
		echo $this->formText($sub);
		echo $errorsHelper($elem);
		echo '</div>';
	} else if (is_array($term[5])) {
        echo '<div class="col-sm-4">';
        echo $this->translate($term[5][0]);
        echo '</div>';
	} else {
        echo '<div class="col-sm-4">';
        echo $this->translate($term[5]);
	    if ($elem->hasAttribute('lang')) {
            echo ' ('.$this->translate($elem->getAttribute('lang')).')';
        }
        echo '</div>';
	}
	echo '</div>'.PHP_EOL;
} // foreach 

    // Page one file summary
    if ($form->page->getValue()==1) {
	    echo '<div class="form-element col-sm-9"><br/>';
		echo '<table class="table table-sm table-striped table-bordered">';
        $i = 0;
		foreach ($form->files as $file) {
            $fview = $file['url']; 
            $fname = basename($fview); 
            $ftime = empty($file['time']) ? ''
                : '<i class="fa fa-clock-o"></i>&nbsp;'.$file['time'].'&nbsp;';
		    echo '<tr><th>';
            if ($form->admin && $fileadmin) {
                echo '<span><a href="'.$fview.'" id="opus:filename'.$i.'">';
                echo $fname.'</a></span><span id="opus:fileadmin'.$i.'"';
                echo ' title="'.$this->translate('File Description').'"';
                echo ' onclick="replace('.$i.')" style="inline; ';
                echo ' cursor:pointer; float:right;">';
                echo $ftime.'<i class="fa fa-edit" aria-hidden="true"></i>';
                echo '</span></th>';
                $i++;
            } else if ($form->admin) {
                echo '<a href="'.$fview.'">'.$fname.'</a></th>';
            } else {
                echo $fname.'</th>';
            }
			echo '</tr>';
        }
		echo '</table>';
		echo '</div>';
        /*
        echo '<div class="help-group col-sm-5">&nbsp;<br>';
        $fcount = $form->get('opus:filecount')->getValue();
        if (count($form->files)==$fcount && $fcount>0) {
            echo $fcount==1?$this->translate('Dpub::filesuccess')
                           :$this->translate('Dpub::filessuccess');
        } else if (count($form->files) < $fcount && count($form->files)>0) {
            echo 'Übertragen Sie weitere Dateien. ';
        }
        echo '</div>';
        */
    }
?>

<?  if ($count==0) { 
        // Metadata and file summary if this was the last page
        echo '<table class="table table-sm table-striped table-bordered">';
        foreach($form->terms as $term) {
	        if ($term[2]=='separator' || $term[2]=='message') {
                continue;
		    } else if ($term[2]=='textbox') {
                continue;
		    } else if ($term[2]=='collection') {
                continue;
		    } else if (empty($form->get($term[0])->getValue())) {
                continue;
		    } else if (empty($form->get($term[0])->getLabel())) {
                continue;
		    } else if ($term[2]=='number' || $term[1]=='Language') {
                continue;
		    } 

            $label = $form->get($term[0])->getLabel();
            $value = $form->get($term[0])->getValue();

            if (is_array($term[2])) {
                $options = $form->get($term[0])->getValueOptions();
                $value = $options[$value];
		    } 
            echo '<tr><td class="col-sm-2">';
            echo $this->translate($label);
            echo '</td><td class="col-sm-10">';
            echo $value;
            echo '</td></tr>';
		}
        $cnt = 0;
        if (empty($form->files)) {
			echo '<tr><td>'.$this->translate('Dpub::File').' '.$cnt.'</td><th>';
        } else foreach ($form->files as $file) {
            $fview = $file['url'];
            $fname = basename($fview); 
            $cnt++;
			echo '<tr><td>'.$this->translate('Dpub::File').' '.$cnt.'</td><th>';
            if ($form->admin) {
                echo '<a href="'.$fview.'">'.$fname.'</a>';
            } else {
                echo $fname;
            }
			echo '</td></th>';
        }
		echo '</table>';
	} 
?>

<?/* Form submit buttons */?>
    <div class="row">
    <div class="control-group col-sm-7">
        <div class="controls">
            <?php if ($form->page->getValue()==$form->end): ?>
                <?php if ($form->admin): ?>
                <button class="btn btn-secondary" type="submit"><?=$this->transEsc('Home')?></button>
                &nbsp;&nbsp;<button class="btn btn-primary" type="submit" name="publish" value="publish"><?=$this->transEsc('Dpub::Publish')?></button>
                <?php else: ?>
                <button class="btn btn-primary" type="submit"><?=$this->transEsc('Home')?></button>
                <?php endif; ?>
            <?php else: ?>
                <button class="btn btn-primary" type="submit" name="submit"><?=$this->transEsc('Submit')?></button>
                <button class="btn btn-secondary" type="submit" name="back" value="back"><?=$this->transEsc('navigate_back')?></button>
            <?php endif; ?>
            &nbsp;&nbsp;
            <?php if ($form->page->getValue()==$form->end-1 && $form->admin): ?>
                <button class="btn btn-secondary" type="submit" name="delete" value="delete"><?=$this->transEsc('Delete')?></button>
            <?php endif; ?>
            &nbsp;&nbsp;
            <?php if ($form->page->getValue()==$form->end-1): ?>
                <a href="<?=$this->url('home')?>">
                <button class="btn btn-secondary" type="button">
                <?=$this->transEsc('confirm_dialog_no')?>
                </button></a>
            <?php endif; ?>
        </div>
    </div>
    <div class="col-sm-5 text-center">
        <?php // echo $form->get('dcterms:identifier')->getValue(); ?>
    </div>
    </div>
</div>
</p>

<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function(){
      $('#upload').hide();
    });
</script>
