<?php

// $this->layout()->searchbox = false;

$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

$errorsHelper  = $this->plugin('formelementerrors');
$errorsHelper->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>');
?>

<div class="opus">
<p>
    <legend>
    <?php echo '<a href="'.$this->url('dbib-info').'?page=1">'
               .$this->translate('New Items').'</a>'; ?>
    <span class="muted">&nbsp;/&nbsp;</span>
    <?php echo '<a href="'.$this->url('dbib-info').'?page=2">'
               .$this->translate('Backtrace').'</a>'; ?>
    <span class="muted">&nbsp;/&nbsp;</span>
    <?php /* echo '<a href="'.$this->url('dbib-info').'?page=3">'
               .$this->translate('Book Bag').'</a>'; */ ?>
    <?php echo '<a href="'.$this->url('dbib-info').'?page=4">'
               .$this->translate('edit_list').'</a>'; ?>
    </legend>
    <table class="table table-xs table-striped table-bordered">

    <?php if ($form->page=='1') { 
        echo '<tr>';
        foreach($form->head as $td) {
            echo '<th>' . $this->translate($td) . '</td>';
        }
        echo '</tr>';
        foreach($form->data as $row) {
            echo $this->form()->openTag($form);
            echo '<tr>';
            echo '<td><a href="/'.$row['uid'].'">'.$row['uid'].'</a>';
            $elem = $form->get('opus:uid');
            $elem->setValue($row['uid']);
            echo $this->formHidden($elem);
            //echo '<span>'.$this->formText($elem).'</span>'."\n";
            echo '</td>'.PHP_EOL;

            echo '<td>';
            $elem = $form->get('opus:ppn');
            $elem->setValue($row['ppn']);
            echo '<span>'.$this->formText($elem).'</span></td>'.PHP_EOL;

            echo '<td>';
            $elem = $form->get('opus:sig');
            $elem->setValue($row['sig']);
            echo '<span>'.$this->formText($elem).'</span></td>'.PHP_EOL;

            echo '<td><small>';
            $elem = $form->get('opus:note');
            $elem->setValue($row['note']);
            echo '<span>'.$this->formTextarea($elem).'</span></small></td>';

            echo '<td>'."\n"; 
            echo '<button class="btn" name="opus:action" type="submit">';
            // echo $this->translate('Send');
            $date = $row['date'] ?? date('Y-m-d');
            echo substr($date,0,10);
            echo '</button></td></tr>'.PHP_EOL; 
            echo $this->form()->closeTag();
        }     
    } else if ($form->page=='2') {    
        echo '<tr>';
        foreach($form->head as $td) {
            echo '<th>' . $this->translate($td) . '</td>';
        }
        echo '</tr>';
        foreach($form->data as $row) {
            echo '<tr>';
            foreach($row as $item) {
                echo '<td>' . $item . '</td>'; 
            }
            echo '</tr>';
        }
    } else if ($form->page=='2') {    
        $row = $form->data[0];
        echo $this->form()->openTag($form);
        echo '<td>';
        $elem = $form->get('opus:uid');
        // $elem->setLabelAttributes(['class' => 'control-label']);
        echo '<span>'.$this->formText($elem).'</span> ';
        echo '</td><td>';

        $elem = $form->get('opus:ppn');
        $elem->setLabelAttributes(['class' => 'control-label']);
        echo '<span>'.$this->formText($elem).'</span> ';
        echo '</td><td>'."\n"; 
        echo '<button class="btn btn-secondary"';
        echo ' name="opus:action" value="ppn">';
        echo $this->translate('Send').'</button>';
        echo '<button class="btn" style="background-color:transparent"';
        echo ' onClick="document.getElementsByName(\'opus&#x3A;source_swb\')';
        echo '[0].value=\'060418435\'"';
        // echo '[0].value=\'380738589\'"';
        // echo '[0].value=\'35173614X\'"';
        echo ' type="button">'.$this->translate($row['text']);
        echo '</button></td>'; 
        echo $this->form()->closeTag();
        echo "</tr>\n"; 
        // }     
    } 
    /*
    } else { 
        echo '<tr>';
        foreach($form->head as $td) {
            echo '<th>' . $this->translate($td) . '</td>';
        }
        echo '</tr>';
        foreach($form->data as $row) {
            echo '<tr>'; 
            foreach($row as $item) {
                echo '<td>' . $item . '</td>'; 
            }
            echo "</tr>\n"; 
        }     
    */
    ?>
    </table>
</p>
</div>

